Assignment 1


Arul Goyal (102303741)

Q1) a.Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [ ]:
import numpy as np
arr= np.array([1,2,3,4,5,6])
reversed= np.flip(arr)
print(reversed)

[6 5 4 3 2 1]


Q2) b.Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods

In [ ]:
arr1= np.array([[1],[2],[3]])
arr1=np.ravel(arr1)
print(arr1)

[1 2 3]


Q3) c. Compare the following numpy arrays:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [ ]:
array1=np.array([[1,2,3],[2,3,4]])
array2= np.array([[1,2,3],[2,3,4]])
print(np.array_equal(array1,array2))

True


Q1) d. Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])


In [ ]:
x = np.array([1, 2, 2, 3, 1, 1])

values, counts = np.unique(x,True)
ind=np.argmax(counts)
most=values[ind]
freq= np.where(x==most)[0]
print(most)
print("Present at")
print(freq)




3
Present at
[3]


In [ ]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y,True)
ind = np.argmax(counts)
most = values[ind]
freq = np.where(y == most)[0]
print(most)
print("Present at")
print(freq)

1
Present at
[0 1 2]


Q1) e. For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find
i. Sum of all elements
ii. Sum of all elements row-wise
iii. Sum of all elements column-wise


In [ ]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
sum_elements=gfg.sum()
print("All elements' sum: ",sum_elements)
sum_row=gfg.sum(axis=1)
print("Row-wise sum: ",sum_row)
sum_col=gfg.sum(axis=0)
print("Column-wise sum: ",sum_col)

All elements' sum:  45
Row-wise sum:  [[14]
 [16]
 [15]]
Column-wise sum:  [[20  9 16]]


Q1) f. Multiply the following matrices and also find covariance between matrices using NumPy:
i. p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
ii. p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]

(i)

In [ ]:
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])

product = np.matmul(p, q)
print(product)

[[16 19]
 [26 31]]


(ii)

In [ ]:
p = np.array([[1, 2], [2, 3], [4, 5]])
q = np.array([[4, 5, 1], [6, 7, 2]])

product = np.matmul(p, q)
print(product)

[[16 19  5]
 [26 31  8]
 [46 55 14]]


Q1) g. Multiply the following matrices and also find covariance between matrices using NumPy:
i. p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
ii. p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]

In [ ]:
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])

product = np.matmul(p, q)
print(product)
p_flat = p.flatten()
q_flat = q.flatten()

combined = np.stack((p_flat, q_flat))  # shape: (2, 4)
covariance = np.cov(combined)
print("Covariance", covariance)


[[16 19]
 [26 31]]
Covariance [[0.66666667 1.        ]
 [1.         1.66666667]]


(ii)

In [ ]:
p_flat = p.flatten()
q_flat = q.flatten()

combined = np.stack((p_flat, q_flat))  # shape: (2, 4)
covariance = np.cov(combined)
print("Covariance", covariance)
p_flat = p.flatten()
q_flat = q.flatten()

combined = np.stack((p_flat, q_flat))  # shape: (2, 6)
covariance = np.cov(combined)
print("Covariance", covariance)


Covariance Matrix:
 [[0.66666667 1.        ]
 [1.         1.66666667]]
Covariance Matrix:
 [[0.66666667 1.        ]
 [1.         1.66666667]]


Q1) (h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?

In [ ]:
from itertools import product
x = np.array([[2, 3, 4],
              [3, 2, 9]])

y = np.array([[1, 5, 0],
              [5, 10, 3]])
inner = np.inner(x, y)
print("Inner Product:",inner)
outer = np.outer(x, y)
print("Outer Product:",outer)
x1 = x.flatten()
y1 = y.flatten()

cartesian = np.array(list(product(x1, y1)))
print("Cartesian Product:", cartesian)

Inner Product: [[17 52]
 [13 62]]
Outer Product: [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian Product: [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


Q2) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])


i. Find element-wise absolute value

In [ ]:
array = np.array([[1, -2, 3],
                  [-4, 5, -6]])
abs_array = np.abs(array)
print("Element-wise Absolute:")
print(abs_array)

Element-wise Absolute:
[[1 2 3]
 [4 5 6]]


ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row

In [ ]:
array = np.array([[1, -2, 3],
                  [-4, 5, -6]])
flat = array.flatten()

p25a = np.percentile(flat, 25)
p50a = np.percentile(flat, 50)
p75a = np.percentile(flat, 75)

print("Flattened Array Percentiles:")
print("25th:", p25a)
print("50th (Median):", p50a)
print("75th:", p75a)
p25b=np.percentile(array, 25, axis=0)
p50b=np.percentile(array, 50, axis=0)
p75b=np.percentile(array, 75, axis=0)

print("Column-wise Percentiles:")
print("25th:", p25b)
print("50th:", p50b)
print("75th:", p75b)
p25c = np.percentile(array, 25, axis=1)
p50c = np.percentile(array, 50, axis=1)
p75c = np.percentile(array, 75, axis=1)

print("Row-wise Percentiles:")
print("25th:", p25c)
print("50th:", p50c)
print("75th:", p75c)


Flattened Array Percentiles:
25th: -3.5
50th (Median): -0.5
75th: 2.5
Column-wise Percentiles:
25th: [-2.75 -0.25 -3.75]
50th: [-1.5  1.5 -1.5]
75th: [-0.25  3.25  0.75]
Row-wise Percentiles:
25th: [-0.5 -5. ]
50th: [ 1. -4.]
75th: [2.  0.5]


iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row

In [ ]:
print("Flattened array")
print("Mean:", np.mean(flat))
print("Median:", np.median(flat))
print("Standard Deviation:", np.std(flat))

print("Each column")
print("Mean:", np.mean(array, axis=0))
print("Median:", np.median(array, axis=0))
print("Standard Deviation:", np.std(array, axis=0))

print("Each row")
print("Mean:", np.mean(array, axis=1))
print("Median:", np.median(array, axis=1))
print("Standard Deviation:", np.std(array, axis=1))

Flattened array
Mean: -0.5
Median: -0.5
Standard Deviation: 3.8622100754188224
Each column
Mean: [-1.5  1.5 -1.5]
Median: [-1.5  1.5 -1.5]
Standard Deviation: [2.5 3.5 4.5]
Each row
Mean: [ 0.66666667 -1.66666667]
Median: [ 1. -4.]
Standard Deviation: [2.05480467 4.78423336]


Q2 b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values

In [ ]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

print("Floor Values:", np.floor(a))
print("Ceiling Values:", np.ceil(a))
print("Truncated Values:", np.trunc(a))
print("Rounded Values:", np.round(a))


Floor Values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling Values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated Values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded Values: [-2. -2. -0.  0.  2.  2.  3.]


Q3) (a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find
i. Sorted array
ii. Indices of sorted array
iii. 4 smallest elements
iv. 5 largest elements

In [ ]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

print("Sorted Array:", np.sort(array))
print("Indices of Sorted Array:", np.argsort(array))
print("4 Smallest Elements:", np.sort(array)[:4])
print("5 Largest Elements:", np.sort(array)[-5:])


Q3) (b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]),
find

i. Integer elements only

ii. Float elements only

In [ ]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

int_elements = array[array == np.floor(array)]
float_elements = array[array != np.floor(array)]

print("Integer Elements:", int_elements)
print("Float Elements:", float_elements)


Integer Elements: [1. 2. 3. 2.]
Float Elements: [1.2 2.2]


Q4) a. Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving greyscaleimg.jpg to greyscaleimg.jpg


In [ ]:
from PIL import Image

def img_to_array(path):
    img = Image.open(path)
    print("hello")

    if img.mode == 'L':
        array = np.array(img)
        np.savetxt('grayscale_image.txt', array, fmt='%d')
        print("Grayscale image saved as grayscale_image.txt")

    elif img.mode == 'RGB':
        array = np.array(img)
        reshaped = array.reshape(-1, 3)
        np.savetxt('rgb_image.txt', reshaped, fmt='%d')
        print("RGB image saved as rgb_image.txt")

img_to_array('greyscaleimg.jpg')




hello
RGB image saved as rgb_image.txt
No file to load.



(b) Load the saved file into jupyter notebook?

In [ ]:
loaded = np.loadtxt("rgb_image.txt", dtype=int)

print("Loaded array shape:", loaded.shape)
print(loaded)

Loaded array shape: (99600, 3)
[[ 89  89  89]
 [ 88  88  88]
 [ 88  88  88]
 ...
 [103 103 103]
 [103 103 103]
 [102 102 102]]
